### PR TITLE
Update QueryClient.md

### PR DESCRIPTION
**Pull request by claasahl**
"logger" option is not present in types (v3.39.2)

### CODE REVIEW

**Comment by TkDodo** [comment]
but it is available in v4 and the docs are for v4

**Comment by claasahl** [comment]
@TkDodo Thanks for the quick reply. Is there a stable version of v4 available?

https://www.npmjs.com/package/react-query?activeTab=versions suggests that v4 was not officially released yet. The latest version seems to be v3.39.2.

**Comment by TkDodo** [comment]
it's `@tanstack/react-query` for almost half a year now!

https://tanstack.com/blog/announcing-tanstack-query-v4

**Comment by claasahl** [comment]
@TkDodo thanks for the pointer 🙇

**Pull request closed without merging**
