### PR TITLE
fix(types): add clear to QueryResultBase

### LINKED ISSUE #692: clear is missing in QueryResult type definition
**Describe the bug**
When calling `useQuery` in a TypeScript project, `clear` is not defined as a valid key of the returned object.

**To Reproduce**
1. Visit https://codesandbox.io/s/youthful-kilby-1ktsq?file=/src/App.tsx
2. See TypeScript error: `Property 'clear' does not exist on type 'QueryResult<unknown, Error>'. ts(2339)`

**Expected behavior**
`clear` should be part of the type definition for `QueryResult`.

**Additional context**
There might be other keys that are currently missing in the type definitions.

### PR DESCRIPTION
**Pull request by MarceloAlves**
Adds type for `clear()` on `QueryResultBase`

closes #692

### CODE REVIEW

**Comment by MichaelDeBoey** [comment]
@all-contributors Please add @MarceloAlves for code

**Comment by MichaelDeBoey** [comment]
This should be added to the docs too

**Comment by MarceloAlves** [comment]
@MichaelDeBoey Ah yes! Will open another PR for that 👍

**Pull request merged**
