### PR TITLE
feat(qwik-query): Qwik Query Adapter for TanStack Query 

### PR DESCRIPTION
**Pull request by gioboa**
This pull request adds Qwik adapter for TanStack Query.

I covered:

- useQuery
- useInfiniteQuery
- userQueries
- useIsFetching
- useMutation
- useIsMutating

It's draft because I need to cover these things

[ ] TypeScript types

To avoid a huge PR with too many lines of code these tasks will be in future PRs
[ ] More tests
[ ] Docs and readme
[ ] Examples

### CODE REVIEW

**Comment by gioboa** [comment]
I need an help with TypeScript types, any help is welcome.

**Comment by TkDodo** [comment]
@gioboa how are we going to continue with this PR please? We're close to merging beta -> rc, and ideally, there wouldn't be any open PRs to beta at that point

**Comment by gioboa** [comment]
Yep, I am working on typescript types. @Puppo is helping me because I need an help for that.

**Comment by gioboa** [comment]
I close this PR so you can go on with your roadmap. I will open another PR against the new TanStack final version. 👍

**Comment by TkDodo** [comment]
@gioboa we could reopen against the `rc` branch if you want?

**Comment by gioboa** [comment]
Thanks 👍

**Comment by TkDodo** [comment]
done, but you'd need to fix the conflicts please.

**Comment by gioboa** [comment]
Yep, thanks 👍

**Pull request closed without merging**
