### PR TITLE
feat(vue-query): add support for infiniteQueryOptions

### PR DESCRIPTION
**Pull request by DavideSegullo**
The goal of this PR is to support the `infiniteQueryOptions` utility as it already does for react:
https://tanstack.com/query/latest/docs/framework/react/reference/infiniteQueryOptions

TODO:

- [x] Add tests

### CODE REVIEW

**Comment by DavideSegullo** [comment]
Hola @TkDodo When you can, could I get some feedback on this PR? Thank you so much!

**Comment by XantreDev** [comment]
It also do not exist for solid-query. Maybe it makes sense to add function type to the core package for easier reuse?

**Comment by DavideSegullo** [comment]
> It also do not exist for solid-query. Maybe it makes sense to add function type to the core package for easier reuse?

Idk if you can share the implementation, some type for example on vue are constrained to vue types, do you have any ideas?

**Comment by XantreDev** [comment]
Probably I need to make contribution with the 95% the same copy pasted code. Because there is not actual logic - only types

**Comment by XantreDev** [comment]
Btw, in this implementation and react implementation pageParams has always `unknown[]` type

**Comment by DavideSegullo** [comment]
> Btw, in this implementation and react implementation pageParams has always `unknown[]` type Is it desirable behvaiour?

Uhm I just followed what was being done on react

**Comment by TkDodo** [comment]
`pageParams` returned from `useInfiniteQuery` has `unknown` as type, yes. There isn't much need to use those during rendering and it was a quick implementation to not have to add more type parameters.

**Comment by XantreDev** [comment]
@TkDodo We already have a parameter for that. The problem that TData do not use it. Since TPageParam is declared after TData - we need to make some trick to do not make backward compatibility
```ts
UseInfiniteQueryOptions<
  TQueryFnData,
  TError,
  TData,
  TQueryFnData,
  TQueryKey,
  TPageParam
>
```

**Review by TkDodo — APPROVED** [review]

**Pull request merged**
