### PR TITLE
fix(solid-query): Don't return promise when data is available synchronously

### PR DESCRIPTION
**Pull request by Brendonovich**
In our application, we have `placeholderData: keepPreviousData` set globally, and try to take full advantage of Suspense and transitions.
We have refetch on window focus enabled, and every time we refocused a suspense boundary was triggering for a tiny amount of time - small enough that the fallback wasn't actually visible, but long enough that solid was modifying DOM elements, causing a CSS fade in animation to constantly retrigger.
With this change, the query resource effectively short circuits if a result is synchronously available (as is the case with `keepPreviousData` after first load), so even if a query is refetching, it won't suspend after first load.

### CODE REVIEW

**Comment by ardeora** [comment]
Hello! Hope you're having a great week. Thanks for fixing this! Some of the tests seem to break. Is it possible you could create a reproduction of this issue? So that I can better understand if there are some edge cases we're not handling

**Comment by Brendonovich** [comment]
Made a repro: https://github.com/Brendonovich/solid-query-suspense-repro
Run it with `pnpm dev`, open the first route, then switch to another tab and back a few times, you'll notice that the CSS transition replays as DOM elements are being modified, also removing the root `Suspense` fixes the issue too.
Not sure why that test isn't passing, I'll keep looking into it.

**Comment by ardeora** [comment]
Ah thank you so much for creating the reproduction! I think I have identified the issue. The issue seems to be in the implementation of the query persistent layer. I'll report back when I have figured out the solution

**Comment by ardeora** [comment]
Thanks for the help on this! @Brendonovich I will be closing this in favor of #6993 and I will give you Co-Author credits there!

**Pull request closed without merging**
