### PR TITLE
[next] Regression tests

### PR DESCRIPTION
**Pull request by cherniavskii**
Hi,
I went through some closed issues and added regression tests 🚀

After adding a test for #137, it appeared that it doesn't work as expected, so I've fixed it in https://github.com/cherniavskii/react-query/commit/e0e81cf1f4d2ec3cd2f66e2346d2de1906764df2

Let me know what you think :)

### CODE REVIEW

**Comment by tannerlinsley** [comment]
This has uncovered some bugs and I'm working on my own merge of `next` into this PR. Hold off for a minute :)

**Comment by cherniavskii** [comment]
Just pushed a commit with resolved merge conflicts.
Not touching that branch from now on

**Comment by cherniavskii** [comment]
BTW, `usePaginatedQuery` tests are failing on `next` branch as well

**Comment by tannerlinsley** [comment]
K, If you would pull in changes from the `pr/148` branch into your feature branch, then we should be good to go.

**Comment by cherniavskii** [comment]
Shouldn't size-plugin.json be added to .gitignore? I just commited it to the repo and it broke size-plugin action

**Comment by tannerlinsley** [comment]
I'm currently changing the way size change stuff works. We'll leave it for now, but in the future, github actions is going to do all of that and the size plugin will simply be used during development and not for PR comments etc.

**Pull request merged**
