### PR TITLE
extend the remove overloads codemod logic

### PR DESCRIPTION
**Pull request by balazsmatepetro**

### CODE REVIEW

**Comment by balazsmatepetro** [comment]
@TkDodo it fixes the second case that @gillkyle provided: https://github.com/TanStack/query/issues/6204

What would be the expected outcome in the following case?

```tsx
export function useDeleteSomething(): any {
  return useMutation(({ groupId }: { groupId: string }) => {
    return fetch(`/api/groups/${groupId}`, {
      method: "DELETE",
    });
  });
}
```

**Comment by TkDodo** [comment]
> What would be the expected outcome in the following case?

```
export function useDeleteSomething(): any {
  return useMutation(({ groupId }: { groupId: string }) => {
    return fetch(`/api/groups/${groupId}`, {
      method: "DELETE",
    });
  });
}
```

it would be:

```
export function useDeleteSomething(): any {
  return useMutation({
    mutationFn: ({ groupId }: { groupId: string }) => {
      return fetch(`/api/groups/${groupId}`, {
        method: "DELETE",
      })
    }
  })
}
```

**Comment by balazsmatepetro** [comment]
> it would be:

Thank you! Once I'm done with this, I will mark the PR as 'Ready for review'.

**Comment by TkDodo** [comment]
@balazsmatepetro is this ready to be merged? What's missing ?

**Pull request merged**
