### PR TITLE
Update community-projects.md - Add Rapini

### PR DESCRIPTION
**Pull request by rametta**
Adding a popular community project that has been around for a few years now. Didn't realize this page existed until today, so adding it

### CODE REVIEW

**Comment by TkDodo** [comment]
thanks. the list is ordered alphabetically and I'd like to keep it that way please

**Comment by rametta** [comment]
> thanks. the list is ordered alphabetically and I'd like to keep it that way please

No problem, updated!

**Review by TkDodo — APPROVED** [review]

**Comment by TkDodo** [comment]
prettier fails ....

**Comment by rametta** [comment]
> prettier fails ....

fixed

**Comment by manudeli** [comment]
> prettier fails ....

I made Pull Request to reduce your repetitive efforts to comment and time to merge like this comment. check https://github.com/TanStack/query/pull/7508 please.

**Pull request merged**
