### PR TITLE
fix(svelte-query): Attempt to stabilise tests

### PR DESCRIPTION
**Pull request by lachlancollins**

### CODE REVIEW

**Comment by lachlancollins** [comment]
@TkDodo I think this has fixed the test build!

**Comment by ZackDeRose** [comment]
👋 @lachlancollins - what was the issue with the svelte tests being unstable? (I had done the migration for tests from jest => vitest here in the `alpha` branch, but iirc, svelte-query was already using vitest in `main` so I left it untouched!)

**Comment by lachlancollins** [comment]
> 👋 @lachlancollins - what was the issue with the svelte tests being unstable? (I had done the migration for tests from jest => vitest here in the `alpha` branch, but iirc, svelte-query was already using vitest in `main` so I left it untouched!)

Not 100% sure - either way, this moves shared dependencies into the monorepo root. This is what I was sent, apparently it's been failing repeatedly: https://github.com/TanStack/query/actions/runs/4425849666/jobs/7761411502

**Comment by ZackDeRose** [comment]
> Not 100% sure - either way, this moves shared dependencies into the monorepo root. This is what I was sent, apparently it's been failing repeatedly: https://github.com/TanStack/query/actions/runs/4425849666/jobs/7761411502

Pasting the logs below for reference. Looks like this is a timining issue, where the `await sleep(20)` doesn't appear to always be enough time for the expected change in the DOM!

I think the best option is to look for sleeps like this and switch them out for `waitFor`s (https://testing-library.com/docs/dom-testing-library/api-async/#waitfor).

```
> nx run @tanstack/svelte-query:"test:lib"


> @tanstack/svelte-query@4.26.1 test:lib /home/runner/work/query/query/packages/svelte-query
> vitest run --coverage true


 RUN  v0.27.1 /home/runner/work/query/query/packages/svelte-query
      Coverage enabled with istanbul

 ❯ src/__tests__/createQueries.test.ts  (1 test | 1 failed) 162ms
   ❯ src/__tests__/createQueries.test.ts > createQueries > Render and wait for success
     → expect(received).toBeInTheDocument()

received value must be an HTMLElement or an SVGElement.

 ✓ src/__tests__/createQuery.test.ts  (1 test) 206ms
 ✓ src/__tests__/createMutation.test.ts  (1 test) 332ms

⎯⎯⎯⎯⎯⎯⎯ Failed Tests 1 ⎯⎯⎯⎯⎯⎯⎯

 FAIL  src/__tests__/createQueries.test.ts > createQueries > Render and wait for success
Error: expect(received).toBeInTheDocument()

received value must be an HTMLElement or an SVGElement.

 ❯ src/__tests__/createQueries.test.ts:34:45
     32|     await sleep(20)
     33| 
     34|     expect(screen.queryByText('Success 1')).toBeInTheDocument()
       |                                             ^
     35|     expect(screen.queryByText('Success 2')).toBeInTheDocument()
     36|   })

⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯[1/1]⎯

 Test Files  1 failed | 2 passed (3)
      Tests  1 failed | 2 passed (3)
   Start at  11:38:37
   Duration  24.23s (transform 6.16s, setup 1.56s, collect 6.31s, tests 700ms)

 % Coverage report from istanbul
-------------------|---------|----------|---------|---------|-------------------
File               | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s 
-------------------|---------|----------|---------|---------|-------------------
All files          |   59.57 |    27.77 |   67.85 |   58.69 |                   
 svelte-query      |     100 |      100 |     100 |     100 |                   
  vitest.setup.ts  |     100 |      100 |     100 |     100 |                   
 svelte-query/src  |   59.13 |    27.77 |   67.85 |   58.24 |                   
  Hydrate.svelte   |       0 |        0 |     100 |       0 | 5-8               
  ...ovider.svelte |       0 |        0 |     100 |       0 | 6-15              
  context.ts       |    87.5 |       50 |     100 |    87.5 | 10                
  ...eBaseQuery.ts |   84.21 |       50 |     100 |   84.21 | 40,46,52          
  ...initeQuery.ts |       0 |      100 |       0 |       0 | 98-99             
  ...teMutation.ts |     100 |      100 |   85.71 |     100 |                   
  createQueries.ts |     100 |      100 |     100 |     100 |                   
  createQuery.ts   |     100 |      100 |     100 |     100 |                   
  useHydrate.ts    |       0 |        0 |       0 |       0 | 9-12              
  useIsFetching.ts |       0 |        0 |       0 |       0 | 21-40             
  useIsMutating.ts |       0 |        0 |       0 |       0 | 21-40             
  ...ueryClient.ts |     100 |      100 |     100 |     100 |                   
-------------------|---------|----------|---------|---------|-------------------
 ELIFECYCLE  Command failed with exit code 1.
```

**Comment by TkDodo** [comment]
i remember re-writing the svelte tests from the `await sleep(20)` approach to `await waitFor`, at least the `createQuery` test:

https://github.com/TanStack/query/commit/1615509973fc4850890f8da028c21b22ba28b829#diff-2bb69226dc4122a1bfac0f33a86d1f9e8cbc089fa2d2ada2d5da3cefce6f7770R8-R26

`createQueries`, on `alpha`, has also been re-written:

https://github.com/TanStack/query/commit/b7ac0c4466976081af6fdc790c767da0d0635e58#diff-50f1c86e3157e46fae30e9861771cf370c20e3fa0cd2c42d3100edbdf6a2a3b6R8-R39

I think the flakiness was reported on `main` where we don't have these changes? Maybe we should backport them?

also, it seems like new tests have been added in the meantime for mutations and another one for `createQuery` that has `sleep(100)` two times in it. I would really like us to move away form the hardcoded sleep approach. Not only can it introduce flakiness, sleep for 200ms means tests will get very slow over time. The async operation might already be finished in a much shorter time ... There's also `sleep(50)` in the queryFn. multiply this by a couple hundrets of tests and we are looking at very slow test execution

we can merge this PR, but we have to please re-write the tests on `main` to follow the recommended testing practices.

**Pull request merged**
