### PR TITLE
fix(react-query): non continuous suspense with useSuspenseQueries (#6298)

### PR DESCRIPTION
**Pull request by maciej-baruch**
#6298

### CODE REVIEW

**Review by TkDodo — COMMENTED** [review]
I had this fix in mind:

```diff
Subject: [PATCH] fix: useQueries suspense
---
Index: packages/react-query/src/useQueries.ts
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/packages/react-query/src/useQueries.ts b/packages/react-query/src/useQueries.ts
--- a/packages/react-query/src/useQueries.ts	
+++ b/packages/react-query/src/useQueries.ts	
@@ -1,7 +1,11 @@
 'use client'
 import * as React from 'react'
 
-import { QueriesObserver, notifyManager } from '@tanstack/query-core'
+import {
+  QueriesObserver,
+  QueryObserver,
+  notifyManager,
+} from '@tanstack/query-core'
 import { useQueryClient } from './QueryClientProvider'
 import { useIsRestoring } from './isRestoring'
 import { useQueryErrorResetBoundary } from './QueryErrorResetBoundary'
@@ -262,9 +266,9 @@
   const suspensePromises = shouldAtLeastOneSuspend
     ? optimisticResult.flatMap((result, index) => {
         const opts = defaultedQueries[index]
-        const queryObserver = observer.getObservers()[index]
 
-        if (opts && queryObserver) {
+        if (opts) {
+          const queryObserver = new QueryObserver(client, opts)
           if (shouldSuspend(opts, result, isRestoring)) {
             return fetchOptimistic(opts, queryObserver, errorResetBoundary)
           } else if (willFetch(result, isRestoring)) {

```

I think we don't need to use the matching observer on the QueriesObserver - the fetch is fire-and-forget anyways, so I just created a `new QueryObserver` to do the fetch.

the `fetchOptimistic` method on the observer is just a small wrapper around `query.fetch()`, so we technically don't even need it ... but changing that could be considered breaking, so this is the most minimal fix I could find. Can you try if your tests also work with that solution?

**Comment by maciej-baruch** [comment]
Nice and simple.
The tests run.

**Review by TkDodo — APPROVED** [review]

**Comment by TkDodo** [comment]
There are some warnings with the way the tests are written:

```
Warning: The current testing environment is not configured to support act(...)
```

maybe relates to:
- https://github.com/testing-library/react-testing-library/issues/1061

not sure if we'd need to update testing-library or vitest or both?

Maybe you could also change the tests to be written more like the other tests that we have? We basically don't test hooks, but wrap them in components like so:

https://github.com/TanStack/query/blob/c014ea7a29db5bdd0770733e3c531c9050d7e4e9/packages/react-query/src/__tests__/suspense.test.tsx#L123-L148

**Comment by maciej-baruch** [comment]
Happy to comply.

**Pull request merged**
