### PR TITLE
build: add turborepo (wip)

### PR DESCRIPTION
**Pull request by zorzysty**
Work in progress

### CODE REVIEW

**Comment by TkDodo** [comment]
even without remote caching, I think we should get a nice boost in PR execution time, e.g. if a PR only touches something in `vue-query`, we wouldn't need to run the tests of `react-query`, right?

could we merge the PR as-is ?

**Comment by TkDodo** [comment]
@zorzysty codesandbox preview builds don't seem to work anymore, have a look at:

- https://ci.codesandbox.io/status/TanStack/query/pr/4659/builds/329924

in case you can't access it, it tries to run `copy:types` but the types don't seem to exist?

```
> query@ build:copyTypes /tmp/9585d232
> cp packages/react-query-devtools/build/lib/index.d.ts packages/react-query-devtools/build/lib/index.prod.d.ts

cp: cannot stat 'packages/react-query-devtools/build/lib/index.d.ts': No such file or directory
 ELIFECYCLE  Command failed with exit code 1.
{ Error: Process rejected with status code 1
    at ChildProcess.<anonymous> (/app/dist/utils/exec.js:20:27)
    at ChildProcess.emit (events.js:198:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12) code: 1 }
 index.production.js ⏤  12.3 kB (+12.3 kB)
created packages/vue-query/build/umd/index.production.js in 1.8s

> query@ build:copyTypes /tmp/9585d232
> cp packages/react-query-devtools/build/lib/index.d.ts packages/react-query-devtools/build/lib/index.prod.d.ts

cp: cannot stat 'packages/react-query-devtools/build/lib/index.d.ts': No such file or directory
 ELIFECYCLE  Command failed with exit code 1.
{ Error: Process rejected with status code 1
    at ChildProcess.<anonymous> (/app/dist/utils/exec.js:20:27)
    at ChildProcess.emit (events.js:198:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12) code: 1 }
```

I think codesandbox just runs the `build` task. I think you removed `pnpm run typecheck` from the build task, but `typecheck` is _also_ what creates the `.d.ts` files 😅

**Review by alexanaro1217 — APPROVED** [review]

**Comment by zorzysty** [comment]
@TkDodo Sorry, I was a bit swamped lately. I'll take a look this weekend.

**Comment by zorzysty** [comment]
> I think codesandbox just runs the build task. I think you removed pnpm run typecheck from the build task, but typecheck is also what creates the .d.ts files sweat_smile

So as far as I understand, the way Turborepo works, when we tell it that `build` command depends on `typecheck` in the schema file, it will run it before running `build`. So we should not include `typecheck` inside `build` script.

The thing is, it only works like that when `build` is run using `turbo run`. And since we don't seem to have control over the command that codesandbox runs, I added a separate `build:turbo` script which is designed to be used with `turbo run` and left original `build` intact for codesandbox to run.

**Comment by TkDodo** [comment]
@zorzysty we can set the `buildCommand` in `ci.json` inside the `.codesandbox` directory:
https://codesandbox.io/docs/learn/sandboxes/ci#configuration-format

**Comment by zorzysty** [comment]
> @zorzysty we can set the `buildCommand` in `ci.json` inside the `.codesandbox` directory: https://codesandbox.io/docs/learn/sandboxes/ci#configuration-format

Nice!
Let's see if this works then: [5e688dc](https://github.com/TanStack/query/pull/4659/commits/5e688dc40653daf8338f200cdae83ae2dbfdd66d)

**Comment by TkDodo** [comment]
our publish script does `pnpm run build`:

https://github.com/TanStack/query/blob/b324a9b87721934154c8b1c3d4447e3719c0a56b/scripts/publish.ts#L376

will that still work? It doesn't run through `turbo`...

**Comment by zorzysty** [comment]
> our publish script does `pnpm run build`:
> 
> https://github.com/TanStack/query/blob/b324a9b87721934154c8b1c3d4447e3719c0a56b/scripts/publish.ts#L376
> 
> will that still work? It doesn't run through `turbo`...

fixed here: [f093858](https://github.com/TanStack/query/pull/4659/commits/f0938585e4e1691d010f79d5283d1607024fc1c9)

**Comment by anthonyshew** [comment]
For that publish script, to hit cache, you may want to try `npx turbo build` or similar!

Disclaimer: I only had a few minutes and couldn't sort through how to mock this publish myself. Untested theory. 😁

**Comment by TkDodo** [comment]
sorry for the late reply - I've decided to go with `nx` for now

**Pull request closed without merging**
