### PR TITLE
feat(client components): add `use client` directive at the top of files having client components

### PR DESCRIPTION
**Pull request by girishsontakke**
This PR is addressing the improvement suggested in #4689.

### CODE REVIEW

**Review by TkDodo — COMMENTED** [review]
Thanks. I think there are still a couple of places missing like:
- `useIsFetching`
- `useIsMutating`
- the devtools
- the `react-query-persist` package

**Comment by TkDodo** [comment]
not sure where all the conflicts are coming from. can you update with main once more please?

**Comment by girishsontakke** [comment]
> not sure where all the conflicts are coming from. can you update with main once more please?

Sure I have removed the conflicts.

**Review by TkDodo — COMMENTED** [review]
there are more things that should be client components. Basically, everything that uses state, effects or context needs to be a client component. I haven't looked at the full list, but:

- `hydrate.tsx` is definitely a client component
- isRestoring.tsx` has react context

**Comment by TkDodo** [comment]
> I think this also means we might want to split any file that has both client components and hooks into two separate ones, like Hydrate.tsx and QueryClientProvider.tsx?

oh yeah, good idea. I think in v5 the `Hydrate` is no longer a problem because we have removed the hook already, but it makes sense for `QueryClientProvider`

**Comment by Ephem** [comment]
I took the liberty of removing the `'use client'` from the hooks files again, but didn't split the files, I think we can do that later. I think `isRestoring.tsx` is another annoying candidate btw:

```tsx
'use client'
import * as React from 'react'

const IsRestoringContext = React.createContext(false)

export const useIsRestoring = () => React.useContext(IsRestoringContext)
export const IsRestoringProvider = IsRestoringContext.Provider
```

Any such context/useContext pattern will need to be split into two files to get good error messages for the `useContext` part..

**Review by Ephem — APPROVED** [review]

**Pull request merged**
