### PR TITLE
fix(perf): optimized perf of listeners removal

### PR DESCRIPTION
**Pull request by Andarist**
prompted by https://twitter.com/BenLesh/status/1656747203531079680

### CODE REVIEW

**Review by benlesh — APPROVED** [review]
LGTM.

Although if you can weather the idempotent add, it would be more efficient to not have to wrap it in an object.

**Comment by Andarist** [comment]
I assumed that it could be considered a breaking change for the current major so I didnt go for it here

**Comment by JacobMGEvans** [comment]
Awesome Twitter to PR community involvement.

**Comment by TkDodo** [comment]
> I assumed that it could be considered a breaking change for the current major so I didnt go for it here

I don't think it would break something, but if we want to be on the safe side, we could merge this to `main` and then remove the object wrapping on the `alpha` branch?

**Comment by Andarist** [comment]
> I don't think it would break something, but if we want to be on the safe side, we could merge this to main and then remove the object wrapping on the alpha branch?

That sounds like a good incremental approach.

**Comment by TkDodo** [comment]
> That sounds like a good incremental approach.

did that here: https://github.com/TanStack/query/commit/049e0c6e56c6314f4042e9c4849244a19e311161

**Pull request merged**
