### PR TITLE
Support staleTime: Infinity

### PR DESCRIPTION
**Pull request by cherniavskii**
See [discussion](https://github.com/tannerlinsley/react-query/discussions/230)

### CODE REVIEW

**Comment by mskelton** [comment]
This should probably be documented in the readme.  @tannerlinsley Thoughts?

**Comment by tannerlinsley** [comment]
Yep. Documentation 👍

**Comment by tannerlinsley** [comment]
Docs can come later, Just open another PR and I'll get it merged.

**Comment by DBjelovuk** [comment]
Little confused as to what effect this has on `cacheTime`? Are queries still garbage collected when inactive for longer than 5 minutes?

**Comment by tannerlinsley** [comment]
Yes. staleTime is only used when a query is active (it is being rendered using some type of `useQuery`-like hook. When there are no more instances, it is marked as inactive, regardless of stale time and will be garbage collected after the `cacheTime` passes.

**Comment by DBjelovuk** [comment]
Ah, gotcha. Would `Infinity` work for `cacheTime` as well?

**Comment by tannerlinsley** [comment]
You know I’m not sure...

**Comment by tannerlinsley** [comment]
Need a PR to do what’s in here: https://github.com/tannerlinsley/react-query/blob/master/src/queryCache.js#L236, but here too: https://github.com/tannerlinsley/react-query/blob/master/src/queryCache.js#L247

**Pull request merged**
