### PR TITLE
Update vue community projects

### PR DESCRIPTION
**Pull request by zhennann**
Model: Unified Data Source

### CODE REVIEW

**Comment by TkDodo** [comment]
I don't understand how this relates to TanStack Query ?

**Comment by zhennann** [comment]
@TkDodo Sorry, I didn't provide enough information before.

Zova is a vue3 framework with ioc container, which provides the `Model` mechanism in the MVC architecture, encapsulating unified data sources through `Model`. So, the base of Zova Model is just `TanStack Query`. For more info, please see: [Zova Model: Unified Data Source](https://zova.js.org/guide/techniques/model/introduction.html)

**Comment by TkDodo** [comment]
please fix the conflicts

**Comment by zhennann** [comment]
@TkDodo The conflicts have been resolved.

**Pull request merged**
