### PR TITLE
docs: remove accidental destructuring of dehydrated state

### PR DESCRIPTION
**Pull request by danielroe**
`__REACT_QUERY_STATE__` is set to the dehydrated state directly on L283; it's not an object with a key.

reverts https://github.com/TanStack/query/pull/4998
closes https://github.com/TanStack/query/pull/5002

### CODE REVIEW

**Comment by TkDodo** [comment]
I'm confused now. We literally just changed this:
- https://github.com/TanStack/query/pull/4998

**Comment by TkDodo** [comment]
@sneridagh ?

**Comment by sneridagh** [comment]
@danielroe @TkDodo I can tell you that it's nested. I spent more than 3h debugging it because of that.

**Comment by danielroe** [comment]
Running the code in the guide results in the following rendered HTML (dummy data):

```html
<script>
  window.__REACT_QUERY_STATE__ = {"mutations":[],"queries":[{"state":{"data":{"name":"name","description":"description","subscribers_count":"subscribers_count","stargazers_count":"stargazers_count","forks_count":"forks_count"},"dataUpdateCount":1,"dataUpdatedAt":1676753194146,"error":null,"errorUpdateCount":0,"errorUpdatedAt":0,"fetchFailureCount":0,"fetchFailureReason":null,"fetchMeta":null,"isInvalidated":false,"status":"success","fetchStatus":"idle"},"queryKey":["repoData"],"queryHash":"[\"repoData\"]"}]};
</script>
```

Maybe the issue is the `posts.tsx` example, which _does_ nest it? We could instead nest it here too (in L283).

**Comment by sneridagh** [comment]
@danielroe Follow the custom SSR framework instructions. Whst comes out of the function in server side is nested. Sorry I'm afk right now.

**Comment by danielroe** [comment]
I am literally doing that.

CleanShot 2023-02-18 at 20 57 29@2x

**Comment by sneridagh** [comment]
I'll check when I'm again in front on my computer. I swear you it was nested (in fact I fixed it by destructuring). I'll check where I'm importing the dehydrate function from.

**Comment by danielroe** [comment]
Of course - no rush at all. I'm not that familiar with Razzle, but is there a chance you might have run something more like:

```ts
window.__REACT_QUERY_STATE__ = ${JSON.stringify({ dehydratedState })};
```

rather than

https://github.com/TanStack/query/blob/e5a7cf805f8e70734da0dd43480cc795d3486065/docs/react/guides/ssr.md?plain=1#L283

**Comment by sneridagh** [comment]
@danielroe @TkDodo doh, mystery solved... you are correct, this was it... 3h debugging it, too much copy paste (from Redux dehydration, it fooled me) and I couldn't see it. You should stay away for a while when you are stuck, they say... Next time will do. Man, I even debugged the <Hidrate /> component.... 🤦 

I'm reverting my PR now. Sorry for all the hassle and noise.

BTW, I'm currently moving from Redux to react-query and it's being kind of a liberation and a source of happiness so far. @TkDodo @tannerlinsley thanks for this amazing library. Very eager to also move to the new router as well.

**Comment by TkDodo** [comment]
I've merged the revert PR. Thank you both 🙏

**Comment by danielroe** [comment]
You're welcome. Happy to help.

**Pull request closed without merging**
