### PR TITLE
fix(react-query-devtools): support cjs in noop build

### PR DESCRIPTION
**Pull request by Songkeys**
Just noticed that someone also made a PR #3883 . But we should export the noop version.

### CODE REVIEW

**Comment by TkDodo** [comment]
Do we need your PR, the other PR, or both?

**Comment by Songkeys** [comment]
Yes. The other PR pointed out the issue but doesn't export for noop actually. This PR should fix them all.

**Comment by TkDodo** [comment]
Thank you very much 🙇‍♂️

**Comment by TkDodo** [comment]
@Songkeys could it be that we point to the wrong direction for the default require exports. It points towards:

```
"require": "./build/cjs/packages/react-query-devtools/src/noop.js",
```

but looking at the build directory when I create a build locally, `noop.js` is in :

`build/cjs/packages/react-query-devtools/noop.js`

so it's _not_ inside the src directory...

**Comment by Songkeys** [comment]
@TkDodo Oops. I'm sorry about this. You are right. Is it a fix yet? Or do you want me to submit another PR?

**Comment by TkDodo** [comment]
another PR would be great, thanks

**Pull request merged**
