### PR TITLE
feat: suspense for useQueries

### LINKED ISSUE #1523: suspense is not working for useQueries
**Describe the bug**

**To Reproduce**

```ts

const DemoA = () => {
  return (
    <Suspense fallback={'loading'}>
      <Works />
    </Suspense>
  );
};
const DemoB = () => {
  return (
    <Suspense fallback={'loading'}>
      <NotWork />
    </Suspense>
  );
};
const Works: React.FC = () => {
  // status success success success
  console.log(
    'status',
    [1, 2, 3]
      .map(
        (v) =>
          ({
            queryKey: ['users', v],
            queryFn: fetchApi,
            suspense: true,
          } as UseQueryOptions),
      )
      .map(useQuery)
      .map(({ status }) => status),
  );

  return null;
};
const NotWork: React.FC = () => {
  // status loading loading loading
  // status success loading loading
  // status success success loading
  // status success success success
  console.log(
    'status',
    useQueries(
      [1, 2, 3].map(
        (v) =>
          ({
            queryKey: ['users', v],
            queryFn: fetchApi,
            suspense: true,
          } as UseQueryOptions),
      ),
    ).map(({ status }) => status),
  );
  return null;
};
```

**Expected behavior**
useQueries should works like the useQuery loop, the result status should be success

**Screenshots**

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: chrome
 - Version: react-query@3.5.5

**Additional context**

### PR DESCRIPTION
**Pull request by TkDodo**
fixes #1523

### CODE REVIEW

**Comment by dante01yoon** [comment]
wow, so now useQueries support suspense? cool!

**Comment by TkDodo** [comment]
@dante01yoon yep, shipped that yesterday with [4.15.0](https://github.com/TanStack/query/releases/tag/v4.15.0). Please try it out and give feedback. I've written two tests and they work and that's about it 😅

**Comment by TkDodo** [comment]
Oh and btw, it fires all requests in parallel, and you can even combine suspense `true` and `false` within the same useQueries call. No fetch waterfalls 🙌

**Comment by dante01yoon** [comment]
Seems work as intended! I think it might be better add some more test codes. May be I can do help with that

**Comment by TkDodo** [comment]
Yes thanks. I'll happily accept PRs that add more tests 🙌

**Comment by dante01yoon** [comment]
I just added two tests based on your previous tests; whether it works on global configuration, check component only amounts after all queries fetched. 
#4502

**Pull request merged**
