### PR TITLE
chore: Fix monorepo issues reported by Sherif

### PR DESCRIPTION
**Pull request by lachlancollins**
[Sherif](https://github.com/QuiiBz/sherif) is a tool designed to detect issues with workspace config. This PR fixes the majority of issues (can't fix the vue version or typescript version warnings).

### CODE REVIEW

**Comment by QuiiBz** [comment]
Hi! You might want to run Sherif (when https://github.com/QuiiBz/sherif/issues/24 is released) as part of the CI, to prevent any regressions from being merged to main.

**Comment by lachlancollins** [comment]
@QuiiBz I'm not sure if it's possible to add since the repo intentionally includes three separate versions of Vue (2.6, 2.7, 3+) - is there a way to ignore mismatched versions for a specific package?

**Comment by QuiiBz** [comment]
> @QuiiBz I'm not sure if it's possible to add since the repo intentionally includes three separate versions of Vue (2.6, 2.7, 3+) - is there a way to ignore mismatched versions for a specific package?

You can either ignore a whole package with `-p` (`--ignore-package`, so `-p @tanstack/query-example-vue-2.6-basic`), or ignore a specific dependency across the monorepo with `-i` (`--ignore-dependency`, so `-i vue`)

**Comment by lachlancollins** [comment]
> You can either ignore a whole package with `-p` (`--ignore-package`, so `-p @tanstack/query-example-vue-2.6-basic`), or ignore a specific dependency across the monorepo with `-i` (`--ignore-dependency`, so `-i vue`)

Oh awesome! Looks like we could run something like: `sherif -i vue -i react-scripts`

@TkDodo thoughts on adding a `test:sherif` script? It literally executes in `1.040968ms` on my system (imagine if prettier or eslint were this fast...)

**Comment by TkDodo** [comment]
sounds good

**Comment by QuiiBz** [comment]
Note: you won't even need to `pnpm install`: [just checkout, setup node & `npx sherif@version`](https://github.com/quiibz/sherif?tab=readme-ov-file#installation)

**Pull request merged**
