### PR TITLE
docs(svelte-query): Rework SvelteKit setup

### PR DESCRIPTION
**Pull request by lachlancollins**
This PR uses some of the lessons learned from #4798 to propose a standardised way to use svelte-query in SvelteKit.

Changes:

- Updated docs with recommended way to initialise svelte-query in SvelteKit
- Provided links to these instructions from the overview
- Added this setup to all existing SvelteKit examples
- Reworked the `hydration` example to match the docs (renamed example to `ssr`)
- Migrated most examples (except `simple`) to SvelteKit

### CODE REVIEW

**Comment by TkDodo** [comment]
hmm I just checked the old examples and they don't really work on the TanStack page. I'm getting:

```
yarn install v1.22.19
info No lockfile found.
[1/4] Resolving packages...
warning svelte-check > svelte-preprocess > magic-string > sourcemap-codec@1.4.8: Please use @jridgewell/sourcemap-codec instead
warning svelte-check > svelte-preprocess > sorcery > sourcemap-codec@1.4.8: Please use @jridgewell/sourcemap-codec instead
⡀ supports-preserve-symlinks-flag@^1.[2/4] Fetching packages...
[-----------------------------------------------------------------------]error @sveltejs/kit@1.0.12: The engine "node" is incompatible with this module. Expected version "^16.14 || >=18". Got "14.19.3"
error Found incompatible module.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
yarn run v1.22.19
$ vite dev
/bin/sh: 1: vite: not found
error Command failed with exit code 127.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
yarn run v1.22.19
$ vite dev
/bin/sh: 1: vite: not found
error Command failed with exit code 127.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
yarn run v1.22.19
$ vite dev
/bin/sh: 1: vite: not found
error Command failed with exit code 127.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
yarn run v1.22.19
$ vite dev
/bin/sh: 1: vite: not found
error Command failed with exit code 127.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by lachlancollins** [comment]
@TkDodo oh I didn't even notice they were broken before. SvelteKit only supports Node 16 and up - any chance the sandbox environment can be updated?

**Comment by TkDodo** [comment]
are they using a lower version of node? I wouldn't know where to customize this. For the preview sandboxes, we use node16:

https://github.com/TanStack/query/blob/4ae99561ca3383d6de3f4aad656a49ba4a17b57a/.codesandbox/ci.json#L5

**Comment by lachlancollins** [comment]
> [-----------------------------------------------------------------------]error @sveltejs/kit@1.0.12: The engine "node" is incompatible with this module. Expected version "^16.14 || >=18". Got "14.19.3"
> error Found incompatible module.

Seems like something is setting it to Node 14 based on this line. I'll try to track down where that might be tomorrow, and I might ask in the discord. Since the setting is probably external to this repository, are you able to merge this as-is, or would you rather I downgrade the `basic` example to Svelte/Vite for now?

**Pull request merged**
