### PR TITLE
Update query-options.md

### PR DESCRIPTION
**Pull request by qqharry21**
I supposed it was a link to https://tanstack.com/query/v5/docs/react/typescript#typing-query-options
If I'm wrong, please cancel my PR, thanks~

### CODE REVIEW

**Comment by TkDodo** [comment]
yes but it should still be "relative", pointing towards:

```
../guides/typescript#typing-query-options
```

**Comment by arnoud-dv** [comment]
The TypeScript doc is not in guides, though.

**Comment by TkDodo** [comment]
ah right, then fix it please 😂 but keep the links relative is all I ask :)

**Comment by qqharry21** [comment]
I just changed the path to relative. Is that right?

**Comment by arnoud-dv** [comment]
> I just changed the path to relative. Is that right?

No, see the suggested changes 😊

**Comment by qqharry21** [comment]
> > I just changed the path to relative. Is that right?
> 
> 
> 
> No, see the suggested changes 😊

Isn't change to this path?
```
../guides/typescript#typing-query-options
```

**Comment by arnoud-dv** [comment]
> Isn't change to this path?
> 
> ```
> ../guides/typescript#typing-query-options
> ```

The correct link is `[with TypeScript](../typescript#typing-query-options)`

I added it as a suggested change in this PR which you can apply by clicking the button or you could change it manually. Thanks!

**Comment by qqharry21** [comment]
> > Isn't change to this path?
> 
> > 
> 
> > ```
> 
> > ../guides/typescript#typing-query-options
> 
> > ```
> 
> 
> 
> The correct link is `[with TypeScript](../typescript#typing-query-options)`
> 
> 
> 
> I added it as a suggested change in this PR which you can apply by clicking the button or you could change it manually. Thanks!
> 
> 

Thank you for your reply. This is my first pull request to open source, I can't find out where your suggested change button that I can click!! Will you mind to tell me where can I click next time if someone ask me to apply~? Thanks!

**Comment by arnoud-dv** [comment]
Should look something [like this](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/incorporating-feedback-in-your-pull-request#applying-suggested-changes). Thanks for reporting and fixing the wrong link!

**Comment by qqharry21** [comment]
> Should look something [like this](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/incorporating-feedback-in-your-pull-request#applying-suggested-changes). Thanks for reporting and fixing the wrong link!

It's the least I can do.
And it's a good lesson for me to learn how to PR in open source ~ Thanks!!!!

**Pull request merged**
