### PR TITLE
ci: Remove codesandbox

### PR DESCRIPTION
**Pull request by lachlancollins**
The GitHub workflow now builds all examples, superseding codesandbox.

Codesandbox has very frustrating restrictions, like not having corepack/pnpm, and how Node "18" always means 18.12.1. This means it refuses to build recent Next.js versions, which require 18.17.0+.

### CODE REVIEW

**Comment by TkDodo** [comment]
We were using codesandbox to create a preview build on the PR. What's the replacement for this please?

**Comment by lachlancollins** [comment]
> We were using codesandbox to create a preview build on the PR. What's the replacement for this please?

All packages and examples were changed to build on GitHub workflow by #6813 , so from what I can tell, CSB wasn't adding anything to the workflow anymore. Is there something we still need CSB for?

**Comment by TkDodo** [comment]
The codesandbox bot was posting a link where the examples are built with the new code. You could play around with that. You could also use the csb preview builds in your own app to manually verify if the change works as expected. 

Also, if a linked issue had a csb reproduction, csb would build that as well with the PR code so that you can verify that the failing reproduction now works. I think that was quite valuable

**Comment by lachlancollins** [comment]
> The codesandbox bot was posting a link where the examples are built with the new code. You could play around with that. You could also use the csb preview builds in your own app to manually verify if the change works as expected.
> 
> Also, if a linked issue had a csb reproduction, csb would build that as well with the PR code so that you can verify that the failing reproduction now works. I think that was quite valuable

Ahh I see - that's quite useful. Would be nice if codesandbox worked a bit better but oh well!

**Pull request merged**
