### PR TITLE
fix(react-query): remove placeholderData from suspense query

### PR DESCRIPTION
**Pull request by HJZzzzz**

### CODE REVIEW

**Review by TkDodo — APPROVED** [review]

**Comment by TkDodo** [comment]
there are some issues on formatting and types

**Comment by HJZzzzz** [comment]
> there are some issues on formatting and types

Fixed the formatting and types.

But the useMutationState test passed in my local.
Idk why it failed in ci.

**Comment by HJZzzzz** [comment]
> there are still formatting issues

The failing tests(useMutation & useMutationState) are not related with the code i changed. And from what i see the test passed in my local? 
Do you have any ideas why its failing in CI?
Screenshot 2024-02-27 at 10 06 36 AM
Screenshot 2024-02-27 at 10 08 39 AM

**Comment by TkDodo** [comment]
> Do you have any ideas why its failing in CI?

flaky tests, ignore it

**Comment by HJZzzzz** [comment]
> > Do you have any ideas why its failing in CI?
> 
> flaky tests, ignore it

I see. Are there any other things i need to revise?

**Pull request merged**
