### PR TITLE
Use funding key in package.json instead of postinstall script

### PR DESCRIPTION
**Pull request by MichaelDeBoey**

### CODE REVIEW

**Comment by tannerlinsley** [comment]
Why not both?! :)

**Comment by MichaelDeBoey** [comment]
@tannerlinsley npm is discouraging it

**Comment by MichaelDeBoey** [comment]
@opencollective too: https://github.com/opencollective/opencollective/issues/2391

**Comment by tannerlinsley** [comment]
Hmmm. Fair enough :)

**Pull request merged**
