### PR TITLE
Introduce Knip

### PR DESCRIPTION
**Pull request by webpro**
This PR introduces [Knip](https://github.com/webpro/knip), a tool to find unused files, dependencies and exports. It can find all sort of unused (or unlisted) things, I'll show example output below.

```
pnpm knip
```

The current results are quite useful imho (see below for an idea).

Lots of unused exports from `__tests__` files. Not sure whether test files should export anything? Those files could be ignored as well (but we'd lose their dependency usage).

This monorepo is such a great exercise for Knip! If we manage to reach "inbox zero" (i.e. no reported issues) I would love to add it to [Knip's integration test suite](https://github.com/webpro/knip/actions/workflows/integration.yml) which should prevent regressions, helping both projects.

Unfortunately I did have to make one change to the codebase: `packages/vue-query-devtools/vite.config.js` has both ESM (`import`) and CJS (`__dirname`) syntax. I think Vite itself bundles its config files using esbuild before execution. This is why I renamed `vite.config.js` Another solution could be to refactor `__dirname` into ESM-compliant code.

I wasn't sure if/how you'd like to a `package.json` script or CI workflow, so I didn't.

Let me know if you have any questions or feedback, happy to discuss any concerns or questions you may have :)

### CODE REVIEW

**Comment by TkDodo** [comment]
@webpro here's an update after I addressed / removed most things:

```
Unused files (1)
packages/vue-query-devtools/src/production.ts
```

I think this is a false-positive. If we look at `vite.config.cjs`, we can see that `src/production.ts` is an entry point:

https://github.com/TanStack/query/blob/6c366099e328d013eebcfbe05c787e37f22476ef/packages/vue-query-devtools/vite.config.cjs#L10-L13

So either the vite config isn't picked up, or the entry points aren't respected.

```
Unused devDependencies (5)
esbuild    package.json                   
type-fest  package.json                   
vue        package.json                   
vue2       packages/vue-query/package.json
vue2.7     packages/vue-query/package.json
```

- I think we need esbuild as it's a peerDependency of `tsup` 🤔 
- `type-fest` is actually used, but only as a type import here:

https://github.com/TanStack/query/blob/7a9d2d080cb52cce9d7e59207ee6ae4807a3c700/scripts/publish.js#L437-L440

I guess JsDoc annotations aren't picked up?

`vue2` and `vue2.7` are needed because we use `vue-demi-switch` to test against different versions of vue:

https://github.com/TanStack/query/blob/84bf7753344a474abb24f1fd2be67e1295cdc206/packages/vue-query/package.json#L40-L42

```
Referenced optional peerDependencies (2)
react-dom             packages/react-query/package.json
@vue/composition-api  packages/vue-query/package.json
```

I don't really know what that means or refers to ... For react-query, we definitely need react-dom as a peerDependency, it's not optional 😅 

```
Unlisted dependencies (1)
test-setup.ts  packages/vue-query-devtools/vitest.config.ts
```

`test-setup.ts` is a file we have, not a dependency, so this report doesn't make much sense to me.

```
Unused exports (61)
initialIsOpen   packages/svelte-query-devtools/src/Devtools.svelte:12:14                                    
buttonPosition  packages/svelte-query-devtools/src/Devtools.svelte:13:14                                    
position        packages/svelte-query-devtools/src/Devtools.svelte:14:14                                    
client          packages/svelte-query-devtools/src/Devtools.svelte:15:14                                    
errorTypes      packages/svelte-query-devtools/src/Devtools.svelte:16:14                                    
styleNonce      packages/svelte-query-devtools/src/Devtools.svelte:17:14                                    
client          packages/svelte-query-persist-client/src/PersistQueryClientProvider.svelte:11:14            
onSuccess       packages/svelte-query-persist-client/src/PersistQueryClientProvider.svelte:12:14            
persistOptions  packages/svelte-query-persist-client/src/PersistQueryClientProvider.svelte:13:14            
key             packages/svelte-query-persist-client/src/__tests__/AwaitOnSuccess/AwaitOnSuccess.svelte:6:14
states          packages/svelte-query-persist-client/src/__tests__/AwaitOnSuccess/AwaitOnSuccess.svelte:7:14
onSuccess       packages/svelte-query-persist-client/src/__tests__/AwaitOnSuccess/Provider.svelte:10:14     
states          packages/svelte-query-persist-client/src/__tests__/AwaitOnSuccess/Provider.svelte:11:14     
queryClient     packages/svelte-query-persist-client/src/__tests__/AwaitOnSuccess/Provider.svelte:7:14      
persistOptions  packages/svelte-query-persist-client/src/__tests__/AwaitOnSuccess/Provider.svelte:8:14      
key             packages/svelte-query-persist-client/src/__tests__/AwaitOnSuccess/Provider.svelte:9:14      
key             packages/svelte-query-persist-client/src/__tests__/FreshData/FreshData.svelte:7:14          
states          packages/svelte-query-persist-client/src/__tests__/FreshData/FreshData.svelte:8:14          
fetched         packages/svelte-query-persist-client/src/__tests__/FreshData/FreshData.svelte:9:14          
key             packages/svelte-query-persist-client/src/__tests__/FreshData/Provider.svelte:10:14          
states          packages/svelte-query-persist-client/src/__tests__/FreshData/Provider.svelte:11:14          
fetched         packages/svelte-query-persist-client/src/__tests__/FreshData/Provider.svelte:12:14          
queryClient     packages/svelte-query-persist-client/src/__tests__/FreshData/Provider.svelte:8:14           
persistOptions  packages/svelte-query-persist-client/src/__tests__/FreshData/Provider.svelte:9:14           
key             packages/svelte-query-persist-client/src/__tests__/InitialData/InitialData.svelte:7:14      
states          packages/svelte-query-persist-client/src/__tests__/InitialData/InitialData.svelte:8:14      
key             packages/svelte-query-persist-client/src/__tests__/InitialData/Provider.svelte:10:14        
states          packages/svelte-query-persist-client/src/__tests__/InitialData/Provider.svelte:11:14        
queryClient     packages/svelte-query-persist-client/src/__tests__/InitialData/Provider.svelte:8:14         
persistOptions  packages/svelte-query-persist-client/src/__tests__/InitialData/Provider.svelte:9:14         
key             packages/svelte-query-persist-client/src/__tests__/OnSuccess/OnSuccess.svelte:5:14          
queryClient     packages/svelte-query-persist-client/src/__tests__/OnSuccess/Provider.svelte:6:14           
persistOptions  packages/svelte-query-persist-client/src/__tests__/OnSuccess/Provider.svelte:7:14           
key             packages/svelte-query-persist-client/src/__tests__/OnSuccess/Provider.svelte:8:14           
onSuccess       packages/svelte-query-persist-client/src/__tests__/OnSuccess/Provider.svelte:9:14           
queryClient     packages/svelte-query-persist-client/src/__tests__/RemoveCache/Provider.svelte:6:14         
persistOptions  packages/svelte-query-persist-client/src/__tests__/RemoveCache/Provider.svelte:7:14         
key             packages/svelte-query-persist-client/src/__tests__/RemoveCache/Provider.svelte:8:14         
key             packages/svelte-query-persist-client/src/__tests__/RemoveCache/RemoveCache.svelte:5:14      
key             packages/svelte-query-persist-client/src/__tests__/RestoreCache/Provider.svelte:10:14       
states          packages/svelte-query-persist-client/src/__tests__/RestoreCache/Provider.svelte:11:14       
queryClient     packages/svelte-query-persist-client/src/__tests__/RestoreCache/Provider.svelte:8:14        
persistOptions  packages/svelte-query-persist-client/src/__tests__/RestoreCache/Provider.svelte:9:14        
key             packages/svelte-query-persist-client/src/__tests__/RestoreCache/RestoreCache.svelte:7:14    
states          packages/svelte-query-persist-client/src/__tests__/RestoreCache/RestoreCache.svelte:8:14    
key             packages/svelte-query-persist-client/src/__tests__/UseQueries/Provider.svelte:10:14         
states          packages/svelte-query-persist-client/src/__tests__/UseQueries/Provider.svelte:11:14         
queryClient     packages/svelte-query-persist-client/src/__tests__/UseQueries/Provider.svelte:8:14          
persistOptions  packages/svelte-query-persist-client/src/__tests__/UseQueries/Provider.svelte:9:14          
key             packages/svelte-query-persist-client/src/__tests__/UseQueries/UseQueries.svelte:7:14        
states          packages/svelte-query-persist-client/src/__tests__/UseQueries/UseQueries.svelte:8:14        
setActTimeout   packages/svelte-query-persist-client/src/__tests__/utils.ts:22:17                           
queryClient     packages/svelte-query/src/HydrationBoundary.svelte:10:14                                    
state           packages/svelte-query/src/HydrationBoundary.svelte:8:14                                     
options         packages/svelte-query/src/HydrationBoundary.svelte:9:14                                     
client          packages/svelte-query/src/QueryClientProvider.svelte:5:14                                   
options         packages/svelte-query/src/__tests__/CreateMutation.svelte:6:14                              
options         packages/svelte-query/src/__tests__/CreateQueries.svelte:5:14                               
queryClient     packages/svelte-query/src/__tests__/CreateQueries.svelte:9:14                               
options         packages/svelte-query/src/__tests__/CreateQuery.svelte:5:14                                 
queryClient     packages/svelte-query/src/__tests__/CreateQuery.svelte:6:14
```

Those are all svelte files, wich I haven't touched, because I don't know svelte and [the docs](https://svelte.dev/docs/svelte-components#script-1-export-creates-a-component-prop) say:

> Svelte uses the export keyword to mark a variable declaration as a property or prop, which means it becomes accessible to consumers of the component

I don't really dare remove those - does knip understand svelte? cc @lachlancollins maybe those can all be removed, don't know ...

---

another thing I had to do was ignore certain `.d.ts` files:

```
ignore: ['**/react-app-env.d.ts', '**/vite-env.d.ts'],
```

at least for the `react-app-env.d.ts`, I know that `react-scripts` (create-react-app) creates that and needs it. If knip understands `react-scripts`, it should probably know that this isn't unused ? I don't know about the vite-env though ...

**Comment by lachlancollins** [comment]
> > Svelte uses the export keyword to mark a variable declaration as a property or prop, which means it becomes accessible to consumers of the component
> 
> I don't really dare remove those - does knip understand svelte? cc @lachlancollins maybe those can all be removed, don't know ...

Definitely can't remove - this is a core feature of svelte v3/v4 props (there will be a new way to do this when v5 is released, but this current way will still be supported).

**Comment by webpro** [comment]
Getting there...

- All the `*.svelte` files were included because of missing semi-colons (the initial regex matched against them).
- JSDoc was parsed, but pretty minimal; improved in latest version.
- There was no support for `build.lib.entry` in Vite plugin yet, added in latest version.

The rest we still need to do:

```
❯ knip
Unused devDependencies (4)
esbuild  package.json                   
^ tsup has esbuild as dependency so I think this can be removed?

vue      package.json                   
^ Unused?

vue2     packages/vue-query/package.json
vue2.7   packages/vue-query/package.json
^ This is super custom stuff, we should add to `ignoreDependencies`

Referenced optional peerDependencies (2)
react-dom             packages/react-query/package.json
^ This is marked as an optional peer dep, so the report seems valid

@vue/composition-api  packages/vue-query/package.json
^ This is probably a bug in Knip, will look into/fix

Unlisted dependencies (1)
test-setup.ts  packages/vue-query-devtools/vitest.config.ts
^ This file does not exist, but it's configured, so either add file or remove from config?

Unused exports (1)
setActTimeout  packages/svelte-query-persist-client/src/__tests__/utils.ts:22:17
^ Unused export
```

**Comment by webpro** [comment]
I think I've fixed the issue with the `@vue/composition-api` false positive. It's kinda complicated... In short (comment in Knip code base):

```
        // A dependency may not be referenced, but it may be a peer dep of another.
        // If that host is also not referenced we'll report this dependency as unused.
        // Except if the host has this dependency as an optional peer dep itself.
```

That last "except..." line is what's fixed today in v3.3.1 and just added to this PR.

So for now I think from Knip perspective we're good :) Happy to hear any questions or feedback!

**Comment by DamianOsipiuk** [comment]
@webpro 
The only think left is
```
Referenced optional peerDependencies (1)
react-dom  packages/react-query/package.json
```
And i think it's false-positive since `react-dom` is used in tests
- https://github.com/TanStack/query/blob/main/packages/react-query/src/__tests__/ssr-hydration.test.tsx#L3
- https://github.com/TanStack/query/blob/main/packages/react-query/src/__tests__/ssr.test.tsx#L4

**Comment by webpro** [comment]
> @webpro The only think left is
> 
> ```
> Referenced optional peerDependencies (1)
> react-dom  packages/react-query/package.json
> ```
> 
> And i think it's false-positive since `react-dom` is used in tests
> 
> * https://github.com/TanStack/query/blob/main/packages/react-query/src/__tests__/ssr-hydration.test.tsx#L3
> * https://github.com/TanStack/query/blob/main/packages/react-query/src/__tests__/ssr.test.tsx#L4

It's reported as an _optional_ peerDependency, but it's referenced. So I think it should not be optional?

**Comment by TkDodo** [comment]
> It's reported as an optional peerDependency, but it's referenced. So I think it should not be optional?

it's optional for consumers because they can also use `react-native` instead. It's not optional for our tests 🤔

**Comment by TkDodo** [comment]
not sure what we'd need to change this to?

https://github.com/TanStack/query/blob/568ce178cc2ebdd9fd8c6ecfd4f5303cb064ad24/packages/react-query/package.json#L64-L76

**Comment by webpro** [comment]
Ah, now I see it's in `devDependencies` as well, that's for the tests. Then it should not be reported by Knip I think. I'll look into it!

**Comment by DamianOsipiuk** [comment]
@TkDodo Well, actually... Why do we list it as `peerDependency` when we do not use it in code anywhere? It should still work without installing it no? We only need `react` as peer dep i guess?

**Comment by TkDodo** [comment]
@DamianOsipiuk yes, I think you're right. We _used to_ have `unstable_batchedUpdates` from `react-dom` or `react-native` respectively, but we don't anymore since v5.

This is such a nice catch - I think we can remove the peerDependency on both react-dom and react-native 🎉

**Comment by DamianOsipiuk** [comment]
@webpro Seems like we are green with minimal config! Awesome 🚀

**Comment by webpro** [comment]
This is great, what a nice team effort! 😎

**Comment by webpro** [comment]
> @webpro this is awesome, thanks for contributing!

My pleasure!

> I might have missed something, can I ask why `svelte-eslint-parser` was added?

If you look up `svelte-eslint-parser` in the report above you can see why: it's referenced in ESLint config files.

**Comment by lachlancollins** [comment]
> If you look up `svelte-eslint-parser` in the report above you can see why: it's referenced in ESLint config files.

Ah I see - it is a [dependency of eslint-plugin-svelte](https://github.com/sveltejs/eslint-plugin-svelte/blob/main/package.json) so it isn't absolutely necessary, but also doesn't change anything I guess :)

**Comment by webpro** [comment]
I think it's a pretty common best practice to try and not rely on transitive dependencies (https://knip.dev/guides/handling-issues/#unlisted-dependencies)

**Pull request merged**
