### PR TITLE
fix(sherif): remove unnecessary option and ignore directory

### PR DESCRIPTION
**Pull request by manudeli**
@TkDodo I saw your feature request in https://github.com/QuiiBz/sherif/issues/41 and feature is added in v7.0.0 of sherif
Thanks to request feature to sherif. I am using this tool and this I needed this feature too.

To resolve [your comment](https://github.com/TanStack/query/pull/6686#issuecomment-1890782727) in https://github.com/TanStack/query/pull/6686 I updated script for sherif. from now we don't have to use unnecessary option(-i react-scripts -i typescript) So cool👍

### CODE REVIEW

**Review by TkDodo — APPROVED** [review]

**Comment by TkDodo** [comment]
not sure how but this is failing on main:

https://cloud.nx.app/runs/oblIhu1Dfj

```
> query@ test:sherif /home/runner/work/query/query
> sherif --ignore-package ./integrations/*

error: unexpected argument './integrations/react-cra5' found

Usage: sherif [OPTIONS] [PATH]
```

Can you please investigate and fix it, or I need to revert. Thanks

**Comment by manudeli** [comment]
> not sure how but this is failing on main:
> 
> https://cloud.nx.app/runs/oblIhu1Dfj
> 
> ```
> > query@ test:sherif /home/runner/work/query/query
> > sherif --ignore-package ./integrations/*
> 
> error: unexpected argument './integrations/react-cra5' found
> 
> Usage: sherif [OPTIONS] [PATH]
> ```
> 
> Can you please investigate and fix it, or I need to revert. Thanks

@TkDodo Revert first please not to affect other branches working, I will investigate it soon

**Comment by manudeli** [comment]
@TkDodo, I started to investigate this issue in https://github.com/QuiiBz/sherif/issues/51

**Comment by QuiiBz** [comment]
Hi, seems like your shell automatically interprets and expand `*`, so the resulting command is indeed incorrect. In that case, you have to wrap the argument in quotes: `sherif --ignore-package "./integrations/*"`

Note that this isn't related to Sherif directly, but I'll update the documentation to include these quotes.

Screenshot 2024-01-22 at 12 45 21

**Pull request merged**
