### PR TITLE
(style): formatting

### PR DESCRIPTION
**Pull request by wolverineks**
adds more files to formatting,
other options:
- add precommit hook to format
- combine eslint + prettier

### CODE REVIEW

**Review by tannerlinsley — COMMENTED** [review]
This needs to be `enabled && (documentIsVisible || refetchIntervalInBackground)`

**Comment by wolverineks** [comment]
> This needs to be `enabled && (documentIsVisible || refetchIntervalInBackground)`

prettier makes the claim that it doesnt change the ast of the code,
this is the way the code was going to execute anyway

if you want i can fix this in a different pr?
especially as this doesnt fail any tests

**Comment by tannerlinsley** [comment]
Right, it didn’t change it here. It was just bad to start. :)

**Comment by wolverineks** [comment]
if you want to make the code suggestion ill accept it

**Comment by tannerlinsley** [comment]
I already fixed in a separate Commit :)

**Pull request merged**
