### PR TITLE
refactor(solid-query): vite-plugin-solid backwards compatibility

### PR DESCRIPTION
**Pull request by ardeora**
Add backwards compatibility to the most popular vite-plugin-solid version (2.3.0) and will also help work with nx.

It also removes the version lock from all solid-query examples

### CODE REVIEW

**Comment by TkDodo** [comment]
Lockfile is outdated, you need to pnpm install and commit it please.

**Comment by TkDodo** [comment]
hmm there seem to be conflicts now @ardeora

**Comment by TkDodo** [comment]
oh damn, I forgot that we already had a PR for this and merged the other one by @zorzysty 

- #4311 

sorry 🙈 . @ardeora I can see that this one did a little bit more, like changing the rollup config. This wasn't done in the other PR.

**Comment by ardeora** [comment]
No worries! I'll rebase my PR with main and only keep the changes that still makes sense 😄

**Comment by killpowa** [comment]
Can this PR be merged? We have this exact issue, and this would solve it in an easy way

**Comment by ardeora** [comment]
ezgif-2-fc4fe6b1cc
 Well I completely borked this branch! 
I opened a new PR https://github.com/TanStack/query/pull/4255 that will fix this 

Closing this PR since it is a duplicate

**Pull request closed without merging**
