### PR TITLE
Feature/ts 4.7

### PR DESCRIPTION
**Pull request by TkDodo**
closes https://github.com/TanStack/query/issues/4674

### CODE REVIEW

**Comment by TkDodo** [comment]
@ardeora I fixed the TS version to 4.7.4 because some examples pulled in 4.8 and we should only have one TS version in the monorepo. Because of this, two type errors now show up in solid query. Can you maybe have a look?

```
Error: packages/solid-query/src/createBaseQuery.ts(48,15): error TS2367: This condition will always return 'false' since the types 'TData | undefined' and 'unique symbol' have no overlap.
Error: packages/vue-query/src/useBaseQuery.ts(132,9): error TS2352: Conversion of type 'ToRefs<{ readonly data: DeepReadonly<UnwrapRef<UnwrapRef<TData>>>; readonly error: DeepReadonly<UnwrapRef<UnwrapRef<TError>>>; ... 21 more ...; readonly fetchStatus: FetchStatus; } | { ...; } | { ...; } | { ...; }>' to type 'UseQueryReturnType<TData, TError, QueryObserverResult<TData, TError>>' may be a mistake because neither type sufficiently overlaps with the other. If this was intentional, convert the expression to 'unknown' first.
```

**Comment by DamianOsipiuk** [comment]
@TkDodo Fixed the error in `vue-query`

**Comment by ardeora** [comment]
@TkDodo Fixed the error in `solid-query` as well 💯

**Comment by TkDodo** [comment]
thank you ❤️

**Pull request merged**
