### PR TITLE
Update solid examples

### PR DESCRIPTION
**Pull request by birkskyum**
solid-start example is broken because the dependencies were outdated.

I updated all the solid examples.

### CODE REVIEW

**Comment by DamianOsipiuk** [comment]
@ardeora @birkskyum This actually broke the pipeline.

**Comment by birkskyum** [comment]
Right, it's probably because `pnpm i` wasn't run after the rebase to sync it all.

**Comment by ardeora** [comment]
Okay I think it's fixed now. I think the issue was that the pnpm-lockfile wasn't resolving the svelte vite plugin types package correctly

**Comment by birkskyum** [comment]
@TkDodo  Great! the initial reason I started this was that I noticed the Solid examples at https://tanstack.com/query/latest didn't load. They still don't, but now they at least seem to work alright when accessed [directly](https://codesandbox.io/p/sandbox/github/tanstack/query/tree/main/examples/solid/simple?embed=1) in codesandbox.


Screenshot 2023-10-20 at 19 37 02

**Comment by DamianOsipiuk** [comment]
It does not work, cause example is named `basic-typescript` instead of `basic`. So if you rename the example folder, it will work.

**Comment by birkskyum** [comment]
You're right. I can see the ci.json says:

```json
  "sandboxes": [
    "/examples/react/basic-typescript",
    "/examples/solid/basic",
    "/examples/svelte/basic",
    "/examples/vue/basic"
  ]
```

 it's probably faster to update https://tanstack.com/query/latest to match those.

**Comment by DamianOsipiuk** [comment]
I would prefer for all adapters to expose `basic` example to avoid putting conditions in multiple places.

**Comment by birkskyum** [comment]
> I would prefer for all adapters to expose `basic` example to avoid putting conditions in multiple places.

In that case there is a PR here:
https://github.com/TanStack/query/pull/6169#issuecomment-1773285732

But it will break this example site which actually uses `basic-typescript`
https://tanstack.com/query/latest/docs/solid/examples/solid/basic-typescript

**Pull request merged**
