### PR TITLE
fix: improve long running task performance in query core

### PR DESCRIPTION
**Pull request by Aghassi**
This addresses two hot spots we have noticed
on a large scale enterprise app when profiling
with chrome. These changes help to cut down
on long running tasks when there are many query
calls on the page

### CODE REVIEW

**Comment by Aghassi** [comment]
This uses parts of https://github.com/TanStack/query/pull/8092 as well

**Comment by Aghassi** [comment]
@tannerlinsley Would you be open to taking this fix? Anything I can provide additionally to help with making it easier to take in? Would love to give this one to the community and not maintain an internal patch if I can.

**Comment by TkDodo** [comment]
> This uses parts of https://github.com/TanStack/query/pull/8092 as well

yeah let’s not mix PRs / improvements please. I have reviewed the Proxy one already and left a comment. I’m also fine with this change in isolation.

**Comment by Aghassi** [comment]
> > This uses parts of #8092 as well
> 
> yeah let’s not mix PRs / improvements please. I have reviewed the Proxy one already and left a comment. I’m also fine with this change in isolation.

Sounds good, I will drop the other diff from this and focus just on the one file

**Comment by Aghassi** [comment]
@TkDodo Updated to just address the one performance issue

**Review by TkDodo — APPROVED** [review]

**Pull request merged**
