### PR TITLE
docs: update return for useQuery

### PR DESCRIPTION
**Pull request by MarceloAlves**
Adds documentation for `clear()` on `useQuery`

### CODE REVIEW

**Comment by MarceloAlves** [comment]
There are a handful of other methods returned but not documented/typed that come from the `queryCache` (`heal()`, `cancel()`, `invalidate()`, etc). Should those be added to the docs/types as well?

**Comment by MichaelDeBoey** [comment]
@MarceloAlves If you want, you can add them too 🙂
Same for typings (in a separate PR) 😉

**Comment by tannerlinsley** [comment]
Query methods themselves are not that public... but I guess people are finding them anyway.

**Comment by MarceloAlves** [comment]
> Query methods themselves are not that public

@tannerlinsley yeah thats what I was wondering. Sure they're available but are they really meant to be documented and used

**Comment by tannerlinsley** [comment]
At this moment, no. If we do decide to expose them properly, then I’ll want to look through them and their signatures to make sure they’re good to go.

**Comment by MarceloAlves** [comment]
Sounds good!

**Pull request merged**
