### PR TITLE
perf(devtools): Memoize Devtools QueryRow

### LINKED ISSUE #4097: Devtools are re-rerendering constantly on every cache update even when closed
### Describe the bug

We are encountering performance issues with the app when using devtools with many queries (around 1000). We are using normalised cache keys, when for example fetch of list items updates data in each single fetch query via setQueryData. 

However in v4, by using `useSyncExternalStore` things got really slow (app freezes for a short time when doing updates).

Is it possible to update devtools by batches, or is it even necessary to "observe" every query when the devtools are closed? 

### Your minimal, reproducible example

-

### Steps to reproduce

-

### Expected behavior

-

### How often does this bug happen?

_No response_

### Screenshots or Videos

_No response_

### Platform

-

### react-query version

v4 3.2.1

### TypeScript version

4.7.4

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by prateek3255**
Fixes #4097

### CODE REVIEW

**Comment by prateek3255** [comment]
@TkDodo I am not really sure why the test is failing here:
image

**Comment by prateek3255** [comment]
@TkDodo I am not sure why but some random useQuery test is failing here:
image

**Comment by TkDodo** [comment]
will you add _not_ rendering the devtools at all when they are collapsed in a separate PR ?

**Comment by prateek3255** [comment]
@TkDodo  Wasn't that already done as part of #4146 ? 

https://github.com/TanStack/query/pull/4146/files#diff-c992b3e7d0c726ede60fddfed04ea2b417fe3f708ba78ab43fe4f82c7d8faa25R511-R512

**Pull request merged**
