### PR TITLE
docs(nextjs-suspense-streaming): Update advanced-ssr.md

### PR DESCRIPTION
**Pull request by deli-ght**
The link should direct on github link

### CODE REVIEW

**Comment by TkDodo** [comment]
I don't think it should.

**Comment by deli-ght** [comment]
Then which page should be shown? it shows error page on website.

**Comment by TkDodo** [comment]
it works for me:

https://tanstack.com/query/v5/docs/framework/react/examples/nextjs-suspense-streaming

Screenshot 2024-04-08 at 09 38 37

**Comment by deli-ght** [comment]
I found out that's why.

When I click the link on site, it direct to https://tanstack.com/query/latest/docs/framework/react/guides/examples/nextjs-suspense-streaming.
But your suggestion link is https://tanstack.com/query/v5/docs/framework/react/examples/nextjs-suspense-streaming

**Pull request closed without merging**
