### PR TITLE
fix(devtools): fix restore/trigger loading cond

### PR DESCRIPTION
**Pull request by judicaelandria**
This PR fix the button trigger loading state
closes https://github.com/TanStack/query/issues/5959

### CODE REVIEW

**Review by TkDodo — CHANGES_REQUESTED** [review]
if I now click `trigger loading`, it doesn't change to `restore loading` either.

not sure why, maybe that state isn't what we're actually looking for 🤷 

@ardeora might be able to help here. Also, we're still missing the tests for the devtools from v4. @ardeora I could start adding them for the react adapter, but I think most tests should actually be for the agnostic `query-devtools` package, right? So I'd need to see one or two examples to get this going because I've never written a test in solid 😬

**Comment by judicaelandria** [comment]
hmm that's weird, I'll have a closer look again to see if I can find the real state

**Comment by judicaelandria** [comment]
@TkDodo I think it should work as expected now

**Review by ardeora — APPROVED** [review]
This is looking good! I can see the expected behavior here. One thing that could also be addressed in this PR maybe that when Trigger loading is clicked. We should disable `Trigger Error` button? Ideally we should be able to trigger an Error while in loading state, but currently seems way more complex to achieve this

**Comment by ardeora** [comment]
> if I now click `trigger loading`, it doesn't change to `restore loading` either.
> 
> not sure why, maybe that state isn't what we're actually looking for 🤷
> 
> @ardeora might be able to help here. Also, we're still missing the tests for the devtools from v4. @ardeora I could start adding them for the react adapter, but I think most tests should actually be for the agnostic `query-devtools` package, right? So I'd need to see one or two examples to get this going because I've never written a test in solid 😬

I have been trying to add the tests. The only issue currently I'm stuck on is we use the `solid-transition-group` package to implement the enter/exit animations. The package itself depends on the `ResizeObserver` API which currently doesn't exist in jsdom so simulating an opening devtools causes error. Trying to find a workaround to that.

**Comment by judicaelandria** [comment]
> We should disable `Trigger Error` button? Ideally we should be able to trigger an Error while in loading state, but currently seems way more complex to achieve this

yes, I'll disable to the button while in loading state

**Comment by TkDodo** [comment]
looks good, but please also disable the `invalidate` and `reset` button, as they will also trigger a refetch. clicking them will make the `restore loading` not work

**Comment by judicaelandria** [comment]
@TkDodo  fixed

**Review by TkDodo — APPROVED** [review]

**Pull request merged**
