### PR TITLE
Make sure query is refetched specified number of times

### PR DESCRIPTION
**Pull request by cherniavskii**
If `retry` is set to 1, I would expect `useQuery` to try once again after fail

### CODE REVIEW

**Comment by cherniavskii** [comment]
That's weird, tests are passing on my machine :/

**Comment by tannerlinsley** [comment]
Hmm Travis env issue maybe?

**Comment by cherniavskii** [comment]
Can you check on your machine?

**Comment by tannerlinsley** [comment]
Passes 😂

**Comment by cherniavskii** [comment]
Hey Travis, WTF?

**Comment by tannerlinsley** [comment]
Wait. I got it to fail locally. Try this:

```js
const rendered = render(<Page />)

    await waitForElement(() => rendered.getByText('error'))

    rendered.debug()

    // query should fail `retry + 1` times, since first time isn't a "retry"
    await waitForElement(() => rendered.getByText('Failed 2 times'))

    rendered.debug()
```

**Comment by tannerlinsley** [comment]
Looks like it never flushes the `error` state because the delay is so small? Thoughts?

**Comment by cherniavskii** [comment]
To minimize the delay i've set `retryDelay` to 1.
Will check if it works

**Comment by tannerlinsley** [comment]
Oooohhhh, I don't think the `error` status is reached until the very end. It stays in the loading state until the final failure or success.

**Comment by tannerlinsley** [comment]
And I am pretty sure that is desired from the UI/UX standpoint out of the box.

**Comment by cherniavskii** [comment]
Yeah, this is fine

**Comment by tannerlinsley** [comment]
Something still doesn't seem right tho. Try logging out the failurCount in the render function....

**Comment by tannerlinsley** [comment]
Oh wait. I forgot to build. I think it's good.  This is what I have now:

```js
it('should retry specified number of times', async () => {
    const queryFn = jest.fn()
    queryFn.mockImplementation(() => {
      return Promise.reject('Error test')
    })

    function Page() {
      const { status, failureCount } = useQuery('test', queryFn, {
        retry: 1,
        retryDelay: 1,
      })

      console.log(failureCount)

      return (
        <div>
          <h1>{status}</h1>
          <h2>Failed {failureCount} times</h2>
        </div>
      )
    }

    const rendered = render(<Page />)

    rendered.getByText('loading')

    // query should fail `retry + 1` times, since first time isn't a "retry"
    await waitForElement(() => rendered.getByText('Failed 2 times'))

    rendered.debug()

    expect(queryFn).toHaveBeenCalledTimes(2)
  })
```

**Comment by cherniavskii** [comment]
Let's try

**Comment by cherniavskii** [comment]
Wow, I had to set 50s timeout to make it pass :D

I don't have a better solution for now, at least it works

**Comment by tannerlinsley** [comment]
That just doesn't seem right though... like something else is wrong.

**Comment by tannerlinsley** [comment]
Have you tested this in the browser and played with it there?

**Comment by cherniavskii** [comment]
Yeah https://codesandbox.io/s/spring-tdd-lzlj6

**Comment by cherniavskii** [comment]
Same with tests - they're passing really fast locally.
That single test takes 4.587s

**Comment by tannerlinsley** [comment]
That seems really strange. I want to get to the bottom of it.

**Comment by tannerlinsley** [comment]
I think I found the reason. `queryCache` is shared among test instances, which are all running in parallel I think...

**Comment by tannerlinsley** [comment]
Well, no, they're in isolated workers.... What is going on!!!

**Comment by iamchanii** [comment]
I'd experienced the issue what almost same it. the test passed on my machine but CI failed by timeout. so I had to google and found a solution.

if this project use Jest, would you like to try `--maxWorkers=2` flag? it is working for my case without increase timeout seconds. but there is a slight drop in performance.

**Comment by cherniavskii** [comment]
@iamchanii Unfortunately that didn't help - https://github.com/tannerlinsley/react-query/pull/168/commits/9f46b36d0e0a2f833f805f5f355e0cfef1c6c6d9

**Comment by cherniavskii** [comment]
> queryCache is shared among test instances

I think this is true, looking into this...

**Comment by tannerlinsley** [comment]
Alright, I found something that might help us debug. Change the queryKey to something other than `test` (or something unique to the entire test suite) and watch it pass 🤯

**Comment by cherniavskii** [comment]
Yeah, I've noticed that too
But I found something else. Which is really weird. Would you have time for a call on Zoom?

**Comment by tannerlinsley** [comment]
Yeah

**Comment by cherniavskii** [comment]
I've sent you a link in Twitter DM

**Pull request merged**
