### PR TITLE
document: add guide for using props as a key of query

### PR DESCRIPTION
**Pull request by S-sohofi**

### CODE REVIEW

**Comment by suneettipirneni** [comment]
As of https://github.com/TanStack/query/pull/7608. You no longer need an intermediate `computed` statement for props. You can just use the getter syntax `() => props.foo` directly. It would probably be worth documenting this as using a computed ref for a simple property access is less efficient than using a getter.

**Comment by S-sohofi** [comment]
> As of #7608. You no longer need an intermediate `computed` statement for props. You can just use the getter syntax `() => props.foo` directly. It would probably be worth documenting this as using a computed ref for a simple property access is less efficient than using a getter.

you mean I should do like this?

```
<script setup>
  const props = defineProps([todoId])
  const queryKey = ['todos', ()=>props.todoId]
  const result = useQuery(queryKey, () => fetchTodoById(todoIdValue.value))
</script>
```
but it didn't work for me.
are these changes merged with the main branch?

**Review by TkDodo — CHANGES_REQUESTED** [review]
not sure what happened here but prettier seems to not handle those setups scripts very well ?

**Comment by S-sohofi** [comment]
@TkDodo i've fixed the problem with prettier.

**Comment by TkDodo** [comment]
> I’ve fixed the problem with prettier.

you’ve worked around prettier. Now prettier runs again and it automatically re-formats again.

see: https://github.com/TanStack/query/pull/8088/commits/9b9c095147eeae6dc2d4f7da1bfcc3b17bc32cf4

**Comment by S-sohofi** [comment]
I've done it in another way, recheck it @TkDodo .

**Comment by TkDodo** [comment]
please use prettier locally; it re-formatted again; gonna close this as it kinda wastes my time, sorry.

**Pull request closed without merging**
