### PR TITLE
docs: Updating v3 example links

### PR DESCRIPTION
**Pull request by nicholasgriffintn**
I noticed this issue myself while looking through the docs last week:

https://github.com/TanStack/query/issues/4054

This PR resolves issues with the example links, which are currently linking to the `main` branch when they should be linking to the `v3` branch.

### CODE REVIEW

**Comment by TkDodo** [comment]
Thank you. Aren't other examples affected as well?

**Comment by nicholasgriffintn** [comment]
> Thank you. Aren't other examples affected as well?

Whoops, yeah sorry, completely slipped my mind

**Review by TkDodo — APPROVED** [review]

**Comment by doliG** [comment]
@TkDodo is this deployed yet ? Cause it look like the link are still broken in the website 🤔 thanks

**Comment by TkDodo** [comment]
@doliG I don't know how this is deployed. I've reached out to @tannerlinsley

**Comment by tannerlinsley** [comment]
I’m working on it.

Tanner Linsley

**Comment by doliG** [comment]
> I’m working on it. Tanner Linsley
> […](#)
> On Aug 26, 2022, 3:29 AM -0600, Dominik Dorfmeister ***@***.***>, wrote: @doliG I don't know how this is deployed. I've reached out to @tannerlinsley — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned.Message ID: ***@***.***>

is there any way to know which version (commit hash or tag) of the documentation is live ?

**Pull request merged**
