### PR TITLE
fix(types): infer the narrowest type with `queryOptions`

### PR DESCRIPTION
**Pull request by Andarist**
fixes https://github.com/TanStack/query/issues/5436

### CODE REVIEW

**Review by TkDodo — APPROVED** [review]
❤️🙏

**Comment by TkDodo** [comment]
@Andarist it seems that with this change, we lost excess property checks on the `queryOptions` function. For example, if I misspell a property (e.g. `stallTime` instead of `staleTime`), I'm not getting any errors:

[TypeScript playground](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgRwK4FMoE8DyYbAQB2AznAL5wBmUEIcA5AAIwCGpbAxgNYD0U6VpxgBaNJiwM4vXnBhYw6EgC44AI3RsAUKEiw4AKjisy47AGFo6arXrM2HIXzNYRnK1JlyFS1Ru1aLngExCQAFAhacCgY2ADS6FiqANoMRKggGlAMALoANFExEgBiRKphAJRwALwAfHAACrbAJOgAdAIkEAA2AG7oYQCsFQXRXiwkIugAHorCU1C0UHAkbN3dACqg1gAmEEpEDPAzLfDKvIWrrOtbIOiqg4ZwAIwADO8F5BVaQA)

We don't have a test for this, but I tried it out with the version from before that PR, and there, it used to work 🤔

**Comment by Andarist** [comment]
This gets tricky - the inferred type is **always** exempt from the excess property check. We need to remember that the excess property check is more like a lint rule than anything else. 

If you want to eat cake and have it too then perhaps this self-validation technique is your best bet: [TS playground](https://www.typescriptlang.org/play?#code/JYOwLgpgTgZghgYwgAgPIAczAPYgM7IDeAUMsgI4Cu0AngNIQ0D8AXMpSANYjYDuIAblIVqUGgDEQrdlx78hZPGDgAbCABVgAWwjSQlLQCNoQgL7FiYGuhQA1VcAAmcSAB51APmQBeIsIDadMigyJyM2DDI6gC6bEEQAB6QII4EYTQRaJg4+MhMUYHRyGwgEABuJsSmQsSOEAgqcFAoMBwIWLgitBgd+O7IicmpWb14HgAUCGz2Kk4uEO4eAJRs6jVU3dm4eOMkZBtiDDRs-gBE+kbQp9EANMIHEiBs40s+XgAKUNhawHgQAHTNPDYFQVcYAViWd0UyhUKk0OjYAEYAAwou6mJZCIA). 

Other than that... a bizarre thing like this could work: [TS playground](https://www.typescriptlang.org/play?#code/MYewdgzgLgBGIEkwDMCmAnVZipgXhgGUBPAWwCMQAbACgEoBuAKCmIAdcA5RFDLHfDFYcQyODzSZsqZi3a4ASqlIgAbqm5gkkzABMAPABUAfIIDeTGDADaAaRgBLMDADWqYqJiGYAQwhe7AF0YVAAPKCxdf25tPmkYAH44VHV0GAAuGFtAzMMg5gBfWV1UYCofTBhkAFdsKAdwGABHaoxiAHk2evAIfUsYAEVW9GJbd0EY3ikcABp+obaAMWcCScl+VDmrQigfKlRDB1JcVYk42aZjGmBMiysWtrHiBMyFkafme+HiZZfB7+Wnxg0D2ByOqD+O1Bh2OhTot2a3yeryR7gYiKWYBRmPRIP2MNQmSh+PBMCKTCYDxGnW6kBodwx73cmWsACIwNUKBhWYEtoyfliYPR8KYAAroECkBwQVAAOkwEGo6hoAFY6Hy8WDjpkAIwABj1cwKjCYQA). This infers each property separately~ to ensure that they were present in the input. Thanks to that we can keep the excess property check "as is" because the target object that is meant to report it is not the target of inference on its own. More work/thought would have to be put into this one to handle the optionality of input properties correctly.

**Comment by TkDodo** [comment]
uuh, let me try out the `validate` approach, that looks great. I'll also add some tests for this. Thank you 🙏

**Pull request merged**
